name: tip100
description: TIP 100 Mobile Application.


publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.16.2 <3.0.0"


dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  flutter_bloc: ^7.3.0
  font_awesome_flutter: ^10.1.0
  percent_indicator: ^4.0.1
  bloc: ^7.2.0
  dio: ^4.0.6

  firebase_core: ^1.12.0
  provider: ^6.0.2
  streaming_shared_preferences: ^2.0.0
  bip39: ^1.0.6
  uuid: 3.0.6
  image_picker: ^0.8.4+9
  flutter_google_places: ^0.3.0
  google_api_headers: ^1.3.0
  google_maps_webservice: ^0.0.19
  cloud_firestore: ^3.1.8
  firebase_storage: ^10.2.7
  eva_icons_flutter: ^3.1.0
  shared_preferences: ^2.0.13
  flutter_svg: ^1.0.3
  cached_network_image: ^3.2.0
  animations: ^2.0.2
  fl_chart: ^0.50.6
  expandable: ^5.0.1
  syncfusion_flutter_gauges: ^20.1.57
  sticky_headers: ^0.2.0
  super_tooltip: ^1.0.1
#  flutter_sound: ^8.1.9
  permission_handler: ^8.1.2
#  assets_audio_player: ^3.0.3+3
#  audio_session: ^0.1.6

  file: ^6.1.0
  searchfield: ^0.6.5
  dropdown_search: ^3.0.1
  customizable_multiselect_field: ^1.0.1
  url_launcher: ^6.1.4
#  timelines: ^0.1.0
  file_picker: ^4.6.1
  fluttertoast: ^8.0.9
  flutter_datetime_picker: ^1.5.1
  timeline_list: ^0.0.6
  flutter_sound_system: ^0.0.9
  path: ^1.8.0
  random_string: ^2.3.1
#  sound_recorder: ^0.0.2

#  scrollable_positioned_list: ^0.3.2


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0
  flutter_native_splash: ^2.1.6


flutter_native_splash:

  background_image: "assets/logo/splash.png"

flutter:
  uses-material-design: true

  assets:
    - assets/icon/
    - assets/bars/
    - assets/bars/notice.svg
    - assets/images/
    - assets/buttons/


  fonts:
    - family: ProductSans
      fonts:
        - asset: assets/fonts/bold_italic.ttf
        - asset: assets/fonts/bold.ttf
          weight: 700
        - asset: assets/fonts/italic.ttf
          style: italic
        - asset: assets/fonts/regular.ttf
